### ISSUE TITLE
This project looks ABANDONED

### ISSUE THREAD

**Issue by andreasabel** [agocorona/Workflow#10]
It looks like this project is abandoned.

Latest `Workflow`, `0.8.3`, does not build with GHC 8.6 or higher.  I published revision 2 that restricts building to GHC <= 8.4: https://hackage.haskell.org/package/Workflow-0.8.3/revisions/

Error is:
```
Control/Workflow.hs:750:7: error:
    • Could not deduce (Control.Monad.Fail.MonadFail STM)
        arising from a do statement
        with the failable pattern ‘Just (Running map)’
```
